- hosts: localhost
  gather_facts: false
  tasks:
    - name: find files.
      find:
        paths: "./release_dir"
        recurse: true
        patterns: "*" #正規表現で検索条件をかく
      register: files_to_copy

    - name: debug msg
      debug:
        msg: "{{files_to_copy}}"