- hosts: localhost
  gather_facts: false
  tasks:
    - name: find files.
      find:
        paths: "{{ playbook_dir }}/release_dir"
        recurse: true
        patterns: "*" #正規表現で検索条件をかく
      register: files_to_copy
      delegate_to: localhost

    - name: debug
      debug:
        msg: "{{ files_to_copy }}"

    - name: release
      copy:
        src: "{{ item.path }}"
        dest: "/var/www/html/{{ item.path.replace(playbook_dir + '/release_dir', '') }}"
      with_items: "{{ files_to_copy.files | select('in', path) | list }}"
