- hosts: localhost
  gather_facts: false
  tasks:
    - name: copy files
      set_fact:
        release_file: "{{ item }}"
      with_fileglob:
        - ./release_dir/*  
      delegate_to: localhost
    
    - name: debug
      debug:
        msg: "{{ release_file }}"