- hosts: localhost
  gather_facts: false
  tasks:
    - name: copy files
      copy:
        src: "{{ item }}"
        dest: /var/www/html
        owner: root
        group: root
        mode: 0644
      with_fileglob:
        - ./release_dir/*